version: "3"
networks:
  netdisk:
volumes:
  tracker_data:
  storage_data:
services:
  redis:
    image: "redis:4.0.9"
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: "always"
    networks:
      - netdisk
  zookeeper:
    image: "zookeeper:3.4.14"
    ports:
      - 2181:2181
    restart: "always"
    networks:
      - netdisk
  mysql:
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=netdisk
      - MYSQL_USER=xuxiake
      - MYSQL_PASSWORD=123456
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/opt/sql
    restart: "always"
    networks:
      - netdisk
  fastdfs_tracker:
    image: delron/fastdfs
    volumes:
      - tracker_data:/var/fdfs
    command: tracker
    restart: "always"
    networks:
      - netdisk
    ports:
      - 22122:22122
  fastdfs_storage:
    image: delron/fastdfs
    environment:
      - TRACKER_SERVER=fastdfs_tracker:22122
    volumes:
      - storage_data:/var/fdfs
    command: storage
    restart: "always"
    depends_on:
      - fastdfs_tracker
    networks:
      - netdisk
    ports:
      - 23000:23000
      - 8888:8888
  web:
    build: ./x-netdisk-web
    volumes:
      - ./logs:/logs
    ports:
      - 8080:8080
    restart: "always"
    networks:
      - netdisk
    depends_on:
      - redis
      - zookeeper
      - mysql
      - fastdfs_tracker
      - fastdfs_storage
  route:
    build: ./x-netdisk-route
    volumes:
      - ./logs:/logs
    ports:
      - 9000:9000
    restart: "always"
    networks:
      - netdisk
    depends_on:
      - redis
      - zookeeper
  quartz:
    build: ./x-netdisk-quartz
    volumes:
      - ./logs:/logs
    ports:
      - 8200:8200
    restart: "always"
    networks:
      - netdisk
    depends_on:
      - redis
      - zookeeper
      - mysql
  chat-server:
    build: ./x-netdisk-chat-server
    volumes:
      - ./logs:/logs
    ports:
      - 8100:8100
      - 9527:9527
    restart: "always"
    networks:
      - netdisk
    depends_on:
      - redis
      - zookeeper
      - mysql
  admin:
    build: ./x-netdisk-admin
    volumes:
      - ./logs:/logs
    ports:
      - 8300:8300
    restart: "always"
    networks:
      - netdisk
    depends_on:
      - redis
      - mysql